//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppOrbusAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANA_ENTREPRISES
    {
        public int id { get; set; }
        public string IdOrbus { get; set; }
        public string NomouRaisonSociale { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> Telephone { get; set; }
        public string TypeEntreprise { get; set; }
        public string Etat { get; set; }
        public Nullable<System.DateTime> DateInscription { get; set; }
        public Nullable<System.DateTime> DateExpiration { get; set; }
        public string LibelleTypeEntreprise { get; set; }
    }
}
