//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppOrbusAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVISE
    {
        public string CODEDEVISE { get; set; }
        public string NOMDEVISE { get; set; }
        public Nullable<double> TAUXDEVISE { get; set; }
        public Nullable<double> TAUXDEVISE1 { get; set; }
    }
}
