//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppOrbusAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOSSIERTPS
    {
        public int NUMERODOSSIERTPS { get; set; }
        public Nullable<int> IDTPSOPERATEUR { get; set; }
        public string IMPORTATIONOUEXPORTATION { get; set; }
        public Nullable<System.DateTime> DATEDOSSIERTPS { get; set; }
        public string NIVEAUEXECUTIONDOSSIERTPS { get; set; }
        public string VALIDE { get; set; }
        public string MOYENTRANSPORT { get; set; }
        public string MODETRANSPORT { get; set; }
        public string LIEUEMBARQUEMENT { get; set; }
        public string LIEUDEBARQUEMENT { get; set; }
        public string LIEUDEDOUANEMENT { get; set; }
        public string NOMOURAISONSOCIALEBENEFICIAIRE { get; set; }
        public string FONCTIONBENEFICIAIRE { get; set; }
        public string PROFESSIONBENEFICIAIRE { get; set; }
        public string ADRESSEBENEFICIAIRE { get; set; }
        public string TELEPHONEBENEFICIAIRE { get; set; }
        public string FAXBENEFICIAIRE { get; set; }
        public string EMAILBENEFICIAIRE { get; set; }
        public string VILLEETATZIPBENEFICIAIRE { get; set; }
        public string PAYSBENEFICIAIRE { get; set; }
        public string NUMERONINEA { get; set; }
        public string NUMEROCQIE { get; set; }
        public string NUMEROCC { get; set; }
        public string NUMERORC { get; set; }
        public string CARACTEREDISPENSE { get; set; }
        public string MODEAVECOUSANSPAIEMENT { get; set; }
        public string OBSERVATIONS { get; set; }
        public string BANQUEDOMICILIATION { get; set; }
        public Nullable<System.DateTime> DATEPREVUEARRIVEEOUDEPART { get; set; }
        public string ASSUREUR { get; set; }
        public Nullable<int> NUMERODOSSIERPERSONNALISE { get; set; }
        public string BENEFICIAIRE { get; set; }
        public string DESTINATAIRE { get; set; }
        public string BPBENEFICIARE { get; set; }
        public string CODEPPM { get; set; }
        public string MODEEXPEDITION { get; set; }
        public string IMPRESSIONOUIOUNON { get; set; }
        public Nullable<int> PRIORITE { get; set; }
        public Nullable<double> UTILISATIONCF { get; set; }
        public string NUMEROPOLICE { get; set; }
        public string COURTIER { get; set; }
        public string TYPEPOLICEABONNEMENT { get; set; }
        public string DEJATRANSFERER { get; set; }
        public string NOMBREARTICLE { get; set; }
        public string DocumentsFinanciers { get; set; }
        public Nullable<int> TRANSITAIRE { get; set; }
        public string CODEBARRE { get; set; }
        public string NUMEROCNI { get; set; }
        public string FichiersAttaches { get; set; }
        public string CIRVIS { get; set; }
        public string TypeDeRegime { get; set; }
        public string RegimeDouanier { get; set; }
        public string RegimeFiscal { get; set; }
        public string REGIME { get; set; }
        public string paye { get; set; }
        public string soldeouinon { get; set; }
        public string ExonereTVA { get; set; }
        public string NumeroAbonne { get; set; }
        public Nullable<System.DateTime> DATETRANSMISSION { get; set; }
        public Nullable<int> NUMERODOSSIERAMENDE { get; set; }
        public string IPCLIENT { get; set; }
        public string USEDURL { get; set; }
        public string INDPERF { get; set; }
        public string NumeroDossier { get; set; }
        public Nullable<int> NumeroOrdre { get; set; }
        public Nullable<System.DateTime> DateDernierModification { get; set; }
        public Nullable<int> IdEntreprise { get; set; }
        public string PaysDeProvenance { get; set; }
        public string PaysDeDestination { get; set; }
        public string PATH_INFOS { get; set; }
        public string NUMEROANOTIFIER { get; set; }
    }
}
