//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppOrbusAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURE
    {
        public int IDTPSFACTURE { get; set; }
        public Nullable<int> NUMERODOSSIERTPS { get; set; }
        public string CODEDEVISE { get; set; }
        public string PROFORMAOUDEFINITIVE { get; set; }
        public string NUMEROFACTUREVENDEUR { get; set; }
        public Nullable<System.DateTime> DATEFACTUREVENDEUR { get; set; }
        public string NOMOURAISONSOCIALEVENDEUR { get; set; }
        public string ADRESSEVENDEUR { get; set; }
        public string TELEPHONEVENDEUR { get; set; }
        public string FAXVENDEUR { get; set; }
        public string EMAILVENDEUR { get; set; }
        public string VILLEETATZIPVENDEUR { get; set; }
        public string PAYSVENDEUR { get; set; }
        public Nullable<double> POIDSNETTOTAL { get; set; }
        public Nullable<double> POIDSBRUTTOTAL { get; set; }
        public Nullable<double> VALEURTOTALDEVISE { get; set; }
        public Nullable<double> VALEURTOTALECFA { get; set; }
        public Nullable<double> COUTASSURANCE { get; set; }
        public Nullable<double> COUTFRET { get; set; }
        public Nullable<double> AUTRESCOUTS { get; set; }
        public Nullable<double> VALEURFOBTOTALEDEVISE { get; set; }
        public Nullable<double> VALEURFOBTOTALECFA { get; set; }
        public string TERMEVENTE { get; set; }
        public string MODALITEREGLEMENT { get; set; }
        public string CODEZONEIMPORTATION { get; set; }
        public string PAYSORIGINE { get; set; }
        public string PAYSPROVENANCE { get; set; }
        public string LIBELLEAUTRESCOUTS { get; set; }
        public string CONDITIONSPAIEMENT { get; set; }
        public string INCOTERMEARTICLES { get; set; }
        public Nullable<double> VALEUREXWTOTALEDEVISE { get; set; }
        public Nullable<double> VALEUREXWTOTALECFA { get; set; }
        public Nullable<double> VALEURCFRTOTALEDEVISE { get; set; }
        public Nullable<double> VALEURCFRTOTALECFA { get; set; }
        public Nullable<double> VALEURFCATOTALEDEVISE { get; set; }
        public Nullable<double> VALEURFCATOTALECFA { get; set; }
        public Nullable<double> VALEURFASTOTALEDEVISE { get; set; }
        public Nullable<double> VALEURFASTOTALECFA { get; set; }
        public Nullable<double> VALEURCPTTOTALEDEVISE { get; set; }
        public Nullable<double> VALEURCPTTOTALECFA { get; set; }
        public Nullable<double> VALEURCIFTOTALEDEVISE { get; set; }
        public Nullable<double> VALEURCIFTOTALECFA { get; set; }
        public Nullable<double> VALEURCIPTOTALEDEVISE { get; set; }
        public Nullable<double> VALEURCIPTOTALECFA { get; set; }
        public Nullable<double> VALEURDAFTOTALEDEVISE { get; set; }
        public Nullable<double> VALEURDAFTOTALECFA { get; set; }
        public Nullable<double> VALEURDDUTOTALEDEVISE { get; set; }
        public Nullable<double> VALEURDDUTOTALECFA { get; set; }
        public Nullable<double> VALEURDDPTOTALEDEVISE { get; set; }
        public Nullable<double> VALEURDDPTOTALECFA { get; set; }
        public Nullable<double> VALEURDEQTOTALEDEVISE { get; set; }
        public Nullable<double> VALEURDEQTOTALECFA { get; set; }
        public Nullable<double> VALEURDESTOTALEDEVISE { get; set; }
        public Nullable<double> VALEURDESTOTALECFA { get; set; }
        public Nullable<double> VALEURINCOTERMDEVISE { get; set; }
        public Nullable<double> VALEURINCOTERMCFA { get; set; }
        public string paysdestination { get; set; }
    }
}
