//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppOrbusAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTS
    {
        public int IDCLIENT { get; set; }
        public string NOMOURAISONSOCIALEBENEFICIAIRE { get; set; }
        public string FONCTIONBENEFICIAIRE { get; set; }
        public string PROFESSIONBENEFICIAIRE { get; set; }
        public string ADRESSEBENEFICIAIRE { get; set; }
        public string TELEPHONEBENEFICIAIRE { get; set; }
        public string FAXBENEFICIAIRE { get; set; }
        public string EMAILBENEFICIAIRE { get; set; }
        public string VILLEETATZIPBENEFICIAIRE { get; set; }
        public string PAYSBENEFICIAIRE { get; set; }
        public string NUMERONINEA { get; set; }
        public string NUMEROCQIE { get; set; }
        public string NUMEROCC { get; set; }
        public string NUMERORC { get; set; }
        public string BENEFICIAIRE { get; set; }
        public string CODEPPM { get; set; }
        public Nullable<System.DateTime> DATEAJOUT { get; set; }
        public Nullable<System.DateTime> USERCREATEDDATE { get; set; }
    }
}
