//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppOrbusAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENIR
    {
        public Nullable<int> IDTPSFACTURE { get; set; }
        public string NUMEROTARIFDOUANE { get; set; }
        public int NUMERODOSSIERTPS { get; set; }
        public string DESIGNATIONCOMMERCIALE { get; set; }
        public string PAYSPROVENANCE { get; set; }
        public string PAYSORIGINE { get; set; }
        public string PAYSDESTINATION { get; set; }
        public string UNITEMESURE { get; set; }
        public Nullable<double> QUANTITEMESURE { get; set; }
        public Nullable<double> POIDSNET { get; set; }
        public Nullable<double> POIDSBRUT { get; set; }
        public Nullable<double> VALEURUNITAIRECFA { get; set; }
        public Nullable<double> VALEURCFA { get; set; }
        public Nullable<double> VALEURUNITAIREDEVISE { get; set; }
        public Nullable<double> VALEURDEVISE { get; set; }
        public Nullable<double> VALEURUNITAIREFOBCFA { get; set; }
        public Nullable<double> VALEURFOBCFA { get; set; }
        public Nullable<double> VALEURUNITAIREFOBDEVISE { get; set; }
        public Nullable<double> VALEURFOBDEVISE { get; set; }
        public int ORDRE { get; set; }
    }
}
