//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppOrbusAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATEUR
    {
        public long IDTPSOPERATEUR { get; set; }
        public string CENTREOUOPERATEURECONOMIQUE { get; set; }
        public string NOMOURAISONSOCIALEOPERATEUR { get; set; }
        public string NOMUTILISATEUR { get; set; }
        public string PRENOMUTILISATEUR { get; set; }
        public string ADRESSEUTILISATEUR { get; set; }
        public string TELUTILISATEUR { get; set; }
        public string MOBILEUTILISATEUR { get; set; }
        public string EMAILUTILISATEUR { get; set; }
        public string NUMEROINSCRIPTIONABONNE { get; set; }
        public string LOGINOPERATEUR { get; set; }
        public string MOTDEPASSEOPERATEUR { get; set; }
        public string ABONNE { get; set; }
        public string AbonneSMS { get; set; }
        public string DEFAULTPASSWORD { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATIONPWD { get; set; }
        public Nullable<System.DateTime> DATEEXPIRATIONCERTIFICAT { get; set; }
        public string DELEGATIONIDAGENT { get; set; }
        public string SIGNATUREKEYIDAGENT { get; set; }
        public string EnrolerOuiNon { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
    }
}
